version: '4'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
  db:
    image: postgres:latest
    container_name: consoledotjob.db
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: devjobsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    volumes:
      - ./.containers/devjobsdb:/var/lib/postgresql/data
