name: Homolog Workflow - Build and Test

on:
  push:
    branches: [ "homolog" ]
  pull_request:
    branches: [ "homolog" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
  # test:
  #   - name: Test
  #     run: dotnet test --no-build --verbosity normal
